CSP-620 Implemented Outer API for Employer Summary
SkillsFundingAgency/das-apim-endpoints pull request #1094
Opened 2023-07-06 08:26 UTC by YuvrajPatil-DFE

2023-07-07 12:24 UTC, DevenKShah commented on src/EmployerAan/SFA.DAS.EmployerAan/Configuration/AanHubApiConfiguration.cs
> +public class AanHubApiConfiguration : InnerApiConfiguration { }
Remove the unnecessary use of base class from shared project. This base class is written for shared clients which we are not using.

2023-07-07 12:24 UTC, DevenKShah commented on src/EmployerAan/SFA.DAS.EmployerAan/Configuration/CommitmentsV2ApiConfiguration.cs
> +public class CommitmentsV2ApiConfiguration : InnerApiConfiguration { }
Remove the unnecessary use of base class from shared project. This base class is written for shared clients which we are not using.

2023-07-07 12:34 UTC, DevenKShah requested changes

2023-07-07 12:34 UTC, DevenKShah commented on src/EmployerAan/SFA.DAS.EmployerAan.UnitTests/Application/Employer/Queries/GetEmployerMemberSummary/GetEmployerMemberSummaryQueryHandlerTests.cs
> +        CancellationToken cancellationToken)
Needs indentation here

2023-07-07 12:34 UTC, DevenKShah commented on src/EmployerAan/SFA.DAS.EmployerAan/Application/Employer/Queries/GetEmployerMemberSummary/GetEmployerMemberSummaryQueryHandler.cs
> +                result.ActiveCount = responseEmployerAccount.GetContent()!.ApprenticeshipStatusSummaryResponse!.FirstOrDefault()!.ActiveCount;
I am assuming this is a list of all the accounts and their respective apprentice counts. We need count of the account that the user is registered with not the first item in the list.

2023-07-07 13:15 UTC, DevenKShah approved these changes

2023-07-07 13:31 UTC, MarkFCain approved these changes

2023-07-20 13:56 UTC, MarkFCain approved these changes

2023-07-20 15:31 UTC, DevenKShah submitted a review, later dismissed

2023-07-24 14:19 UTC, MarkFCain submitted a review, later dismissed

2023-07-24 14:19 UTC, DevenKShah approved these changes

2023-07-26 14:57 UTC, MarkFCain approved these changes

2023-07-27 13:05 UTC, merged