FAT2-156_add_search_by_postcode
SkillsFundingAgency/das-apim-endpoints pull request #126
Opened 2020-09-09 13:04 UTC by robyoung91

2020-09-09 14:43 UTC, PeterDavidWilliams commented on src/SFA.DAS.FindApprenticeshipTraining.UnitTests/InnerApi/Requests/WhenBuildingTheGetLocationByFullPostcodeRequest.cs
> +        public void Then_The_Request_Is_Correctly_Encoded_For_Special_Characters(string baseUrl, string fullPostcode)
This test doesn't guarantee that there's a special character in the url. Can you modify `fullPostcode` to include a special character requiring encoding?

2020-09-09 14:43 UTC, PeterDavidWilliams commented on src/SFA.DAS.FindApprenticeshipTraining.UnitTests/InnerApi/Requests/WhenBuildingTheLocationQueryRequest.cs
> +        public void Then_The_Request_Is_Correctly_Encoded_For_Special_Characters(string baseUrl, string query)
This test also doesn't guarantee a special character needing encoding, see above

2020-09-09 15:25 UTC, PeterDavidWilliams approved these changes

2020-09-09 16:46 UTC, dashton82 requested changes

2020-09-09 16:46 UTC, dashton82 commented on src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/LocationHelper.cs
> +            if (Regex.IsMatch(location, @"^[A-Za-z]{1,2}\d[A-Za-z\d]?\s*\d[A-Za-z]{2}$"))
either pull that regex into a variable that describes the check, or pull the whole check into a method describing what its doing

2020-09-09 16:46 UTC, dashton82 commented on src/SFA.DAS.FindApprenticeshipTraining.UnitTests/InnerApi/Requests/WhenBuildingTheLocationQueryRequest.cs
> +        [Test, AutoData]
need some inlineautodata here with some special chars

2020-09-09 16:46 UTC, dashton82 commented on src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Models/WhenCastingGetLocationSearchResponseFromMediatorType.cs
>      }
Could do with some tests/assertions showing that the Name is a concatenation of the LocationName and LocalAuthorityName when the postcode is null, and also for using the postcode when that is not null or empty string

2020-09-10 13:44 UTC, dashton82 submitted a review, later dismissed

2020-09-14 10:33 UTC, dashton82 approved these changes

2020-09-14 10:34 UTC, merged