CSP-1379: Get Employer Relationships - Outer API endpoint.
SkillsFundingAgency/das-apim-endpoints pull request #1483
Opened 2024-05-29 07:26 UTC by shaun-downey-education

- Added a **EmployerRelationshipsController** to the **EmployerPR** API as a route through to the **SFA.DAS.PR.Api**

2024-05-29 11:01 UTC, PeterDavidWilliams approved these changes

2024-05-31 18:07 UTC, DevenKShah requested changes
Build has failed as the Operation enum has been moved

2024-05-31 18:07 UTC, DevenKShah commented on src/Shared/SFA.DAS.SharedOuterApi/Models/Operation.cs
Why was this moved out of our namespace?

2024-06-03 08:40 UTC, shaun-downey-education commented on src/Shared/SFA.DAS.SharedOuterApi/Models/Operation.cs
@DevenKShah The Operation class was duplicated in a few different places so I put it in Models as it is technically an entity linked model.

2024-06-06 14:52 UTC, closed without merging