Aad 283 contentful integration
SkillsFundingAgency/das-apim-endpoints pull request #1538
Opened 2024-06-29 15:06 UTC by alireid

2024-07-09 16:12 UTC, CathyGroom commented on src/ApprenticeApp/SFA.DAS.ApprenticeApp/Application/Commands/SupportAndGuidance/AddUpdateApprenticeArticleCommandHandler.cs
> +
whitespace

2024-07-09 16:16 UTC, CathyGroom commented on src/ApprenticeApp/SFA.DAS.ApprenticeApp/Application/Commands/SupportAndGuidance/AddUpdateApprenticeArticleCommandHandler.cs
Line 21: whitespace

2024-07-09 16:21 UTC, CathyGroom commented on src/ApprenticeApp/SFA.DAS.ApprenticeApp/Services/ContentService.cs
Do we need logging if the get by id methods return null?

2024-07-09 16:24 UTC, CathyGroom commented on src/ApprenticeApp/SFA.DAS.ApprenticeApp.Api/Controllers/SupportAndGuidanceController.cs
Line 55: if the query result is added to the return method it resolves the warning on line 50

2024-07-09 16:25 UTC, CathyGroom requested changes
All looks really good.  Just commented on a couple of issues.

2024-07-09 16:33 UTC, alireid commented on src/ApprenticeApp/SFA.DAS.ApprenticeApp/Services/ContentService.cs
I think so.. just so that we know the method has been hit, in a case where this has been deployed and we can't step into code all we would have is the logs and I believe it may be handy in a circumstance to follow through the stack to determine where problems may be.

2024-07-09 16:35 UTC, alireid commented on src/ApprenticeApp/SFA.DAS.ApprenticeApp.Api/Controllers/SupportAndGuidanceController.cs
Ah yes, handy to return the result. I dont think we are using GetOneByEntryId as at now, but I surfaced it in case we ever do. Added that in though.

2024-07-09 18:33 UTC, CathyGroom approved these changes
Approved.

2024-07-10 08:12 UTC, CathyGroom approved these changes
Approved.

2024-07-18 15:50 UTC, CathyGroom approved these changes
Approved.

2024-07-18 16:07 UTC, merged