FAT2-206 filter providers by rating
SkillsFundingAgency/das-apim-endpoints pull request #157
Opened 2020-10-01 11:16 UTC by dashton82

2020-10-07 09:17 UTC, PeterDavidWilliams requested changes

2020-10-07 09:17 UTC, PeterDavidWilliams commented on src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Models/WhenCastingToProviderBaseTypesFromMediatorType.cs
> +            response.Should().NotBeNull();
Can you modify this so that instead of it just not checking for null, it checks for what it actually should be

2020-10-07 12:10 UTC, scottywakefield approved these changes

2020-10-07 13:21 UTC, PeterDavidWilliams approved these changes

2020-10-12 14:51 UTC, scottywakefield approved these changes

2020-10-12 14:51 UTC, merged