QF2050-select_provider_email_apim
SkillsFundingAgency/das-apim-endpoints pull request #1604
Opened 2024-08-06 09:41 UTC by karen-hanna

2024-08-08 10:08 UTC, ChrisJWoodcock requested changes

2024-08-08 10:35 UTC, karen-hanna commented on src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining.Api/AppStart/AddServiceRegistrationExtension.cs
> +            services.AddTransient<IProviderCoursesApiClient<ProviderCoursesApiConfiguration>, ProviderCoursesApiClient>();
removed

2024-08-08 10:35 UTC, karen-hanna commented on src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining.Api/AppStart/AddConfigurationOptionsExtension.cs
> +            services.Configure<ProviderCoursesApiConfiguration>(configuration.GetSection(nameof(RoatpV2ApiConfiguration)));
removed

2024-08-08 10:35 UTC, karen-hanna commented on src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining.Api/AppStart/AddConfigurationOptionsExtension.cs
> +            services.AddSingleton(cfg => cfg.GetService<IOptions<ProviderCoursesApiConfiguration>>().Value);
removed

2024-08-08 10:36 UTC, karen-hanna commented on src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining.Api/Controllers/EmployerRequestsController.cs
> +        [HttpGet("provider/{ukprn}/emails")]
updated

2024-08-08 16:00 UTC, ChrisJWoodcock requested changes

2024-08-09 08:33 UTC, karen-hanna commented on src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining/Application/Queries/GetProviderEmailAddresses/GetProviderEmailAddressesQueryHandler.cs
> +                .Select(pc => pc.ContactUsEmail.RemoveWhitespace()) ?? Enumerable.Empty<string>())
So ( i think) line 38 allows for providercourses to be null and selects all non-empty strings.  Them line 39 selects the results of that and returns an empty enumerable<stsring> if there are no results (i.e. if the providercourses was null or empty).

2024-08-09 11:04 UTC, karen-hanna commented on src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining/Application/Queries/GetProviderEmailAddresses/GetProviderEmailAddressesQueryHandler.cs
> +                .Where(phone => !string.IsNullOrWhiteSpace(phone))
updated to email

2024-08-09 13:36 UTC, ChrisJWoodcock requested changes

2024-08-09 13:36 UTC, ChrisJWoodcock commented on src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining/Application/Queries/GetProviderEmailAddresses/GetProviderEmailAddressesQueryHandler.cs
> +                .Select(pc => pc.ContactUsEmail.RemoveWhitespace()) ?? Enumerable.Empty<string>())
I read that as if providerCourses is empty it return null and does a .Select on the null.

var emailAddresses = (providerCourses?
	.Select(pc => pc.ContactUsEmail) ?? Enumerable.Empty<string>())
	.Append(request.UserEmailAddress)
	.Select(email => email.RemoveWhiteSpace())
	.Where(email => !string.IsNullOrEmpty(email))
	.Distinct()
	.Order()
	.ToList();

2024-08-09 13:36 UTC, ChrisJWoodcock commented on src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining/Application/Queries/GetProviderEmailAddresses/GetProviderEmailAddressesQueryHandler.cs
> +                .Select(pc => pc.ContactUsEmail.RemoveWhitespace()) ?? Enumerable.Empty<string>())
See comment below

2024-08-09 14:35 UTC, karen-hanna commented on src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining/Application/Queries/GetProviderEmailAddresses/GetProviderEmailAddressesQueryHandler.cs
> +                .Select(pc => pc.ContactUsEmail.RemoveWhitespace()) ?? Enumerable.Empty<string>())
i will defer to your authority on this matter

2024-08-09 15:12 UTC, ChrisJWoodcock submitted a review, later dismissed

2024-08-16 13:10 UTC, ChrisJWoodcock approved these changes

2024-08-21 12:54 UTC, ChrisJWoodcock approved these changes

2024-08-21 12:54 UTC, merged