QF-2070 Training request page
SkillsFundingAgency/das-apim-endpoints pull request #1645
Opened 2024-09-05 13:35 UTC by ChrisJWoodcock

2024-09-09 11:09 UTC, karen-hanna requested changes

2024-09-10 17:15 UTC, ChrisJWoodcock commented on src/EmployerRequestApprenticeTraining/SFA.DAS.EmployerRequestApprenticeTraining.Api/Controllers/EmployerRequestsController.cs
> +        public async Task<IActionResult> GetActiveEmployerRequest([FromRoute] long accountId, [FromRoute] string standardReference)
Renamed to HasExistingEmployerRequest

2024-09-10 17:15 UTC, ChrisJWoodcock commented on src/EmployerRequestApprenticeTraining/SFA.DAS.EmployerRequestApprenticeTraining/InnerApi/Requests/GetEmployerRequestRequest.cs
> +
Done

2024-09-11 08:18 UTC, karen-hanna approved these changes

2024-09-12 13:40 UTC, merged