Aad 690 optel integration new
SkillsFundingAgency/das-apim-endpoints pull request #1778
Opened 2024-11-11 17:46 UTC by tdavande

unit tests added

2024-11-11 18:31 UTC, dashton82 requested changes
There is the option to add Telemetry with metrics in the shared project. This will then align it with use of the Business Metrics API.

2024-11-19 16:43 UTC, alireid approved these changes

2024-11-20 16:36 UTC, alireid requested changes
Two tests needs fixing to pass

2024-11-28 11:22 UTC, alireid approved these changes
approved in principle, await test

2024-11-29 15:09 UTC, dashton82 approved these changes

2024-11-29 15:11 UTC, merged