FAI-2039 Swagger annotations for GetVacancyResponse and CreateVacancyRequest
SkillsFundingAgency/das-apim-endpoints pull request #1812
Opened 2024-11-27 16:55 UTC by LACrossley

2024-12-02 08:15 UTC, dashton82 requested changes

2024-12-02 11:13 UTC, LACrossley commented on src/Vacancies/SFA.DAS.Vacancies.Api/Models/GetVacancyWageItem.cs
> -        public WageUnit WageUnit { get; set; }
I have reinserted this into the latest commit.

2024-12-02 16:47 UTC, dashton82 submitted a review, later dismissed

2024-12-17 15:00 UTC, dashton82 approved these changes

2025-01-03 11:12 UTC, merged