EI-610 set active collection calendar period
SkillsFundingAgency/das-apim-endpoints pull request #213
Opened 2020-11-30 09:38 UTC by David-B-Read

2020-12-01 09:15 UTC, ruslanss commented
@Stephek had a good idea for a database constraint to only allow 1 active calendar period record. do you think we can add it as part of this story?

2020-12-08 10:32 UTC, David-B-Read commented
> @Stephek had a good idea for a database constraint to only allow 1 active calendar period record. do you think we can add it as part of this story?

The inner API enforces only one active collection calendar period

2020-12-14 15:39 UTC, Stephek requested changes

2020-12-14 15:39 UTC, Stephek commented on src/SFA.DAS.EmployerIncentives.Api/Controllers/CollectionCalendarController.cs
> +        [Route("/collectionCalendar/period/active")]
Shouldn't this be /collectionPeriods and the patch is just the CollectionPeriod data to be updated

2020-12-14 15:39 UTC, Stephek commented on src/SFA.DAS.EmployerIncentives.Api/Models/ActivateCollectionCalendarPeriodRequest.cs
> +    public class ActivateCollectionCalendarPeriodRequest
I think this is just a CollectionPeriodRequest with Number, Year and IsActive.  It doesn't make sense to call it Activate... when the Active field could be false.

2020-12-15 08:28 UTC, Stephek submitted a review, later dismissed

2020-12-18 16:38 UTC, ruslanss approved these changes

2020-12-23 12:32 UTC, merged