FAT2-287 epao register api (decommish fat v1 in DC)
SkillsFundingAgency/das-apim-endpoints pull request #214
Opened 2020-12-01 18:30 UTC by scottywakefield

2020-12-03 10:33 UTC, dashton82 requested changes

2020-12-03 10:33 UTC, dashton82 commented on src/SFA.DAS.EpaoRegister/Application/Epaos/Queries/GetEpaoCourses/GetEpaoCoursesQueryHandler.cs
> +            await Task.WhenAll(courseTasks);
not sure if its worth getting all the courses
``` 
var coursesTask = _cacheHelper.GetRequest<GetStandardsListResponse>(_coursesApiClient,
                new GetStandardsListRequest(), nameof(GetStandardsListResponse), out var saveToCache);
```
and saving to cache - then iterating over the cached list for the courses that you want

2020-12-03 10:33 UTC, dashton82 commented on src/SFA.DAS.EpaoRegister/InnerApi/Requests/GetEpaoRequest.cs
> +        public string EpaoId { get; set; }
not sure we do everywhere but it would probably be better to have this set in the constructor

2020-12-03 10:33 UTC, dashton82 commented on src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Requests/GetStandardRequest.cs
> +    public class GetStandardRequest : IGetApiRequest // todo: remove once merged up to date
Can that be removed now?

2020-12-03 10:33 UTC, dashton82 commented on src/SFA.DAS.EpaoRegister/InnerApi/Requests/GetEpaoCoursesRequest.cs
> +        public string GetAllUrl => $"api/ao/assessment-organisations/{EpaoId}/standards";
not sure we do everywhere but it would probably be better to have this set in the constructor

2020-12-03 10:35 UTC, scottywakefield commented on src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Requests/GetStandardRequest.cs
> +    public class GetStandardRequest : IGetApiRequest // todo: remove once merged up to date
lol yes

2020-12-04 12:46 UTC, dashton82 approved these changes

2020-12-14 15:35 UTC, PeterDavidWilliams approved these changes

2020-12-15 09:38 UTC, merged