FAT2-296 recruit outer api
SkillsFundingAgency/das-apim-endpoints pull request #234
Opened 2021-01-13 16:08 UTC by scottywakefield

2021-01-13 16:45 UTC, dashton82 requested changes

2021-01-13 16:45 UTC, dashton82 commented on src/SFA.DAS.Recruit.UnitTests/Application/InnerApi/Requests/WhenBuildingTheGetProviderRequest.cs
> +        public void Then_The_Url_Is_Correctly_Build(int id)
can maybe delete this and the request - since its not used 😬

2021-01-13 16:45 UTC, dashton82 commented on src/SFA.DAS.Recruit/InnerApi/Requests/GetProviderRequest.cs
> +    public class GetProviderRequest : IGetApiRequest
can be deleted 🗑️

2021-01-13 18:04 UTC, dashton82 submitted a review, later dismissed

2021-01-18 10:18 UTC, adam230594 commented on azure-pipelines.yml
> +      ServiceConnection: SFA-DIG-PreProd (ARM)
This should now be SFA-DIG-PreProd-ARM

2021-01-20 15:11 UTC, PeterDavidWilliams approved these changes

2021-01-20 15:25 UTC, merged