Fat2 363 epao availiability
SkillsFundingAgency/das-apim-endpoints pull request #235
Opened 2021-01-14 15:38 UTC by PeterDavidWilliams

2021-01-15 11:18 UTC, dashton82 requested changes

2021-01-15 11:18 UTC, dashton82 commented on src/SFA.DAS.FindEpao.Api/Models/GetCourseEpaoListItem.cs
> +        public DateTime? EffectiveFrom { get; set; }
Not convinced this should be nullable

2021-01-15 15:20 UTC, PeterDavidWilliams commented on src/SFA.DAS.FindEpao.Api/Models/GetCourseEpaoListItem.cs
> +        public DateTime? EffectiveFrom { get; set; }
change made

2021-01-15 15:32 UTC, PeterDavidWilliams commented on src/SFA.DAS.FindEpao.Api/Models/GetCourseEpaoListItem.cs
> +        public DateTime? EffectiveFrom { get; set; }
Change made

2021-01-18 11:34 UTC, dashton82 approved these changes

2021-01-20 12:52 UTC, merged