SV-485 get standard options list
SkillsFundingAgency/das-apim-endpoints pull request #303
Opened 2021-03-02 14:03 UTC by ben1stone

2021-03-02 15:03 UTC, DevenKShah requested changes
Need a few things fixed. Also unit test for conversion of GetStandardOptionsListItem => GetStandardOptionsItem might help.

2021-03-02 15:03 UTC, DevenKShah commented on IntegrationTests/Outer API Tests For Standards.postman_collection.json
> +			"name": "Courses - Get List - None",
Might I suggest to create a separate collection for options.

2021-03-02 15:14 UTC, ben1stone commented
Reverted commit 611df02 as these tests have been added to their own collection

2021-03-02 16:32 UTC, CodeWolf86 commented
I've changed the base to be SV-372 as that will be our next branch to deploy, It contains the new Assessors Outer Api changes with new detail endpoint, so can include the options work as well.

This should coincide with SV-484 and SV-482 of courses api as our next deliverable

2021-03-08 16:51 UTC, CodeWolf86 approved these changes

2021-03-11 17:15 UTC, ben1stone commented
Closed - a new branch has been created and merged

2021-03-11 17:15 UTC, closed without merging