Aedb 30 add sectors
SkillsFundingAgency/das-apim-endpoints pull request #364
Opened 2021-04-27 08:10 UTC by PeterDavidWilliams

2021-04-27 11:35 UTC, dashton82 requested changes

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.Api/Controllers/DemandController.cs
> +            string location, int? locationRadius, List<string> sectors)
This isn't needed on here

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.Api/Controllers/DemandController.cs
> +        public async Task<IActionResult> GetAggregatedCourseDemandList([FromRoute]int ukprn, int? courseId, string location, int? locationRadius, List<string> sectors)
Pretty sure you'll need to add the attribute [FromQuery] to the `List<string>`

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.Api/Controllers/DemandController.cs
> +                    Sectors = sectors
Can be removed

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.UnitTests/Application/Demand/Queries/WhenHandlingGetAggregatedCourseDemandListQuery.cs
> +        public async Task Then_Gets_Sectors_From_Cache(
Can we update where it says Sectors to be Routes instead?

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.UnitTests/Application/Demand/Queries/WhenHandlingGetEmployerCourseProviderDemandQuery.cs
> +﻿using System.Collections.Generic;
These file changes probably aren't required

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.UnitTests/InnerApi/WhenCreatingGetAggregatedCourseDemandListRequest.cs
>          }
Can we also cover the scenario for route to be null as well

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand/Application/Demand/Queries/GetEmployerCourseProviderDemand/GetEmployerCourseProviderDemandQuery.cs
> +        public List<string> Sectors { get; set; }
this can be removed

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand/Application/Demand/Queries/GetEmployerCourseProviderDemand/GetEmployerCourseProviderDemandQueryHandler.cs
> +
These file changes can be undone

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand/InnerApi/Requests/GetCourseProviderDemandsRequest.cs
> +        public GetCourseProviderDemandsRequest(int ukprn, int courseId,  double? lat = null, double? lon = null, int? radius = null)
can undo these file changes

2021-04-27 11:35 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand/InnerApi/Requests/GetRoutesListRequest.cs
> +    public class GetRoutesListRequest :IGetApiRequest
need a test for this

2021-04-27 11:41 UTC, scottywakefield requested changes
I think it's confusing to have sectors and routes, when they are both the same thing. As Courses API refers to them as routes then that's what they should be called elsewhere (except on ui where they're named according to user research).

2021-04-27 11:41 UTC, scottywakefield commented on src/SFA.DAS.EmployerDemand/Application/Demand/Queries/GetAggregatedCourseDemandList/GetAggregatedCourseDemandListResult.cs
> +        public List<GetRoutesListItem> Sectors { get; set; }
are these routes or sectors?

2021-04-27 11:41 UTC, scottywakefield commented on src/SFA.DAS.EmployerDemand/InnerApi/Requests/GetAggregatedCourseDemandListRequest.cs
> +        public string GetUrl => $"api/demand/aggregated/providers/{Ukprn}?courseId={CourseId}&lat={Lat}&lon={Lon}&radius={Radius}&routes=" + string.Join("&routes=", Sectors.Select(HttpUtility.UrlEnco
routes

2021-04-27 11:41 UTC, scottywakefield commented on src/SFA.DAS.EmployerDemand/InnerApi/Requests/GetAggregatedCourseDemandListRequest.cs
> +            Sectors = sectors;
roooooooooooooutes

2021-04-27 11:41 UTC, scottywakefield commented on src/SFA.DAS.EmployerDemand/InnerApi/Requests/GetCourseProviderDemandsRequest.cs
> +using System.Web;
plz check if these using are needed, doesn't seem to be any other change to this file.

2021-05-04 18:48 UTC, dashton82 approved these changes

2021-05-04 20:16 UTC, dashton82 approved these changes

2021-05-04 20:17 UTC, merged