Am 495 allow menu items to be built from cms
SkillsFundingAgency/das-apim-endpoints pull request #435
Opened 2021-07-09 13:37 UTC by sscaife

2021-07-15 06:36 UTC, dashton82 requested changes

2021-07-15 06:36 UTC, dashton82 commented on src/SFA.DAS.Campaign.Api.UnitTests/Controllers/Menu/WhenGettingTheMenu.cs
> +            actualResult.Menu.MainContent.TopLevel.Should().NotBeNullOrEmpty();
Might be worth expanding on this with :
```
mockMediator.Verify(x=>x.Send(It.Is<GetMenuQuery>(c=>c.MenuType.Equals("TopLevel")), CancellationToken.None), Times.Once);
            mockMediator.Verify(x=>x.Send(It.Is<GetMenuQuery>(c=>c.MenuType.Equals("Apprentices")), CancellationToken.None), Times.Once);
            mockMediator.Verify(x=>x.Send(It.Is<GetMenuQuery>(c=>c.MenuType.Equals("Employers")), CancellationToken.None), Times.Once);
            mockMediator.Verify(x=>x.Send(It.Is<GetMenuQuery>(c=>c.MenuType.Equals("Influencers")), CancellationToken.None), Times.Once);
```

2021-07-15 06:36 UTC, dashton82 commented on src/SFA.DAS.Campaign/ExternalApi/Requests/GetMenuRequest.cs
> +    public class GetMenuRequest : IGetApiRequest
Think there is a test missing for this 🤔

2021-07-19 09:58 UTC, dashton82 submitted a review, later dismissed

2021-07-21 13:08 UTC, dashton82 approved these changes

2021-07-21 13:17 UTC, sony-kotha commented
Test completed.

2021-07-21 13:18 UTC, sony-kotha commented
Testing compled.

2021-07-21 13:20 UTC, merged

2021-07-21 13:20 UTC, sony-kotha commented
Testing completed.