[TM-40] Enter Contact Details
SkillsFundingAgency/das-apim-endpoints pull request #444
Opened 2021-07-16 11:43 UTC by mmiddleton3301

APIM endpoints for entering contact details when applying for an opportunity.

See also: https://github.com/SkillsFundingAgency/das-levy-transfer-matching-web/pull/38

2021-07-20 10:52 UTC, chrisfoster76 requested changes

2021-07-21 08:54 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Models/GetContactDetailsRequest.cs
> +    public class GetContactDetailsRequest
Doesn't appear to be - good spot. Removed.

2021-07-21 09:00 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/OpportunityController.cs
> +            var result = await _mediator.Send(new GetContactDetailsQuery()
Done.

2021-07-21 09:04 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetContactDetails/GetContactDetailsHandler.cs
> +                return null;
I personally like to provide the 'happy'/`true` path first, in an `if` statement; I find it more readable.

I've changed this, however.

2021-07-22 09:37 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetContactDetails/GetContactDetailsResult.cs
> +        public int OpportunityAmount { get; set; }
I did this because the response was a composite of different data. I've removed it, however.

2021-07-22 11:26 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Models/GetContactDetailsResponse.cs
> +    public class GetContactDetailsResponse
This has been done.

2021-07-22 11:28 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetContactDetails/GetContactDetailsHandler.cs
> +                    OpportunityLevelDescriptions = allLevels.Where(x => pledge.Levels.Contains(x.Id)).Select(x => x.ShortDescription), // Note: levels here are different - the ShortDescription is use
This has been done.

2021-07-23 11:10 UTC, chrisfoster76 requested changes
Some comments below.

In addition, I've noticed running this locally that the cachekey gets lost from the querystring when applying. This doesn't occur in `main` as it currently stands. This would be a major defect. so worth investigating, and maybe throwing some kind of exception in `RetrieveCacheItem` if they supplied key is = `Empty`

Ugh, this comment was meant for the UI PR.

2021-07-26 09:53 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetContactDetails/GetContactDetailsHandler.cs
> +                JobRoles = allJobRoles.Where(x => pledge.JobRoles.Contains(x.Id)),
Updated all selected reference data properties to send over only the ids, also updated web project to reflect this.

2021-07-26 12:30 UTC, mmiddleton3301 commented
I noticed that the `cacheKey` was being dropped on the back buttons, as I wasn't including it in the view model upon load. I've fixed this now.

2021-07-26 13:04 UTC, chrisfoster76 submitted a review, later dismissed

2021-07-29 12:56 UTC, chrisfoster76 approved these changes

2021-07-29 12:57 UTC, merged