CSP-31 Fixed spelling error in the folder name
SkillsFundingAgency/das-apim-endpoints pull request #690
Opened 2022-04-21 20:51 UTC by DevenKShah

2022-04-22 07:11 UTC, MarkFCain commented on src/SFA.DAS.Roatp.CourseManagement/Application/Provider/GetProviderQueryHandler.cs
> +
remove space

2022-04-22 07:12 UTC, MarkFCain requested changes

2022-04-22 07:12 UTC, MarkFCain commented on src/SFA.DAS.Roatp.CourseManagement/Application/Provider/GetProviderQueryHandler.cs
> +
can we have tests on this?

2022-04-26 14:13 UTC, DevenKShah commented
This is irrelevant

2022-04-26 14:13 UTC, closed without merging