CSP-105-Outer-ConfirmRegulatedStandard
SkillsFundingAgency/das-apim-endpoints pull request #737
Opened 2022-06-09 13:42 UTC by raviudari01

2022-06-13 06:15 UTC, DevenKShah requested changes

2022-06-13 06:15 UTC, DevenKShah commented on src/SFA.DAS.Roatp.CourseManagement.Api/Controllers/ProviderCourseEditController.cs
> +        [Route("providers/{ukprn}/courses/{larsCode}/update-confirm-regulated-standard")]
The endpoint has two verbs in it, change to `update-approved-by-regulator`

2022-06-13 15:17 UTC, DevenKShah requested changes
One small change required.

2022-06-13 15:17 UTC, DevenKShah commented on src/SFA.DAS.Roatp.CourseManagement/Application/Standards/Commands/UpdateApprovedByRegulator/UpdateApprovedByRegulatorCommand.cs
> +        public bool? IsApprovedByRegulator { get; set; }
This cannot be null. As the user is trying to update the value, we should never allow null here.

2022-06-14 20:00 UTC, DevenKShah approved these changes

2022-06-15 07:31 UTC, MarkFCain approved these changes

2022-06-15 15:24 UTC, DevenKShah commented on src/SFA.DAS.Roatp.CourseManagement/InnerApi/Requests/UpdateProviderCourse.cs
> +    public class UpdateProviderCourse
ProviderCourseUpdateModel

2022-06-15 15:24 UTC, DevenKShah commented on src/SFA.DAS.Roatp.CourseManagement.UnitTests/Application/Standards/Commands/UpdateContactDetailsCommandHandlerTests.cs
> +        }
Tests missing for conversion from Command to Request model. Same set of tests should be added to other handler as well.

2022-06-17 09:02 UTC, MarkFCain approved these changes

2022-06-17 10:46 UTC, merged