CSP-184-Outer-AddVenueAndDelivery
SkillsFundingAgency/das-apim-endpoints pull request #817
Opened 2022-08-12 09:59 UTC by raviudari01

2022-08-15 07:35 UTC, DevenKShah requested changes
LocationName should be removed from the payload. Inner API endpoint is not correct.

2022-08-15 07:35 UTC, DevenKShah commented on src/RoatpCourseManagement/SFA.DAS.RoatpCourseManagement/Application/Standards/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommand.cs
> +        public string LocationName { get; set; }
LocationName is not required to be passed in, is it?

2022-08-15 07:35 UTC, DevenKShah commented on src/RoatpCourseManagement/SFA.DAS.RoatpCourseManagement/Application/Standards/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandHandler.cs
> +                _logger.LogError("Create provider course location name :{locationname} for ukprn: {ukprn} larsCode: {larsCode} did not come back with successful response", request.LocationName, reque
Can use location navigation id here instead of location name and include this id in the exception message as well.

2022-08-15 07:35 UTC, DevenKShah commented on src/RoatpCourseManagement/SFA.DAS.RoatpCourseManagement/InnerApi/Requests/ProviderCourseLocationCreateRequest.cs
> +        public string PostUrl => $"providers/{Ukprn}/courses/{LarsCode}/create-providercourselocation";
POST to `providers/{ukprn}/courses/{larscode}/locations`

2022-08-17 07:46 UTC, MarkFCain commented on src/RoatpCourseManagement/SFA.DAS.RoatpCourseManagement/InnerApi/Requests/ProviderCourseLocationCreateRequest.cs
> +    }
don't see any coverage to check mapping from AddProviderCourseLocationCommand

2022-08-17 07:57 UTC, MarkFCain approved these changes
There's a request to add some minor coverage

2022-08-17 08:02 UTC, DevenKShah approved these changes

2022-08-17 12:16 UTC, MarkFCain approved these changes

2022-08-18 12:21 UTC, merged