MAP-171-Move end points over to use new API in reservations
SkillsFundingAgency/das-apim-endpoints pull request #954
Opened 2022-11-30 13:05 UTC by ratheeshri1984

2022-12-05 09:12 UTC, cofaulco requested changes
couple of suggestions

2022-12-05 09:12 UTC, cofaulco commented on src/Reservations/SFA.DAS.Reservations/Application/Providers/Queries/GetProvider/GetProviderQueryHandler.cs
> +            GetProviderResponse providers=null;
singular `provider` for variable name

2022-12-05 09:12 UTC, cofaulco commented on src/Reservations/SFA.DAS.Reservations/Application/Providers/Queries/GetProvider/GetProviderQueryHandler.cs
> +                var provider = await _roatpApiClient.Get<GetRoatpProviderResponseSummary>(
rename to `roatpProviderResponse`

2022-12-05 09:43 UTC, ratheeshri1984 commented on src/Reservations/SFA.DAS.Reservations/Application/Providers/Queries/GetProvider/GetProviderQueryHandler.cs
> +            GetProviderResponse providers=null;
Done

2022-12-05 09:43 UTC, ratheeshri1984 commented on src/Reservations/SFA.DAS.Reservations/Application/Providers/Queries/GetProvider/GetProviderQueryHandler.cs
> +                var provider = await _roatpApiClient.Get<GetRoatpProviderResponseSummary>(
No change

2022-12-05 12:57 UTC, cofaulco approved these changes

2023-02-02 11:55 UTC, cofaulco approved these changes

2023-02-02 12:04 UTC, merged